server:
  port: 9527
spring:
  application:
    name: product-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///huangou-product?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
